title: "Juana Granados"
url: "juanagranadosr.github.io"
remote_theme: ankitsultana/researcher@gem
baseurl: ""

favicon: true
favicon_location: "/favicon-32.png"
apple_touch_icon_location: "/favicon.png"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 #- name: "About"
 #  link: "/researcher/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Intuition Lab"
   link: "intuition-lab/"
 - name: "Contact"
   link: "contact"
